activemq:
  broker-url: vm://embedded-broker?create=true&broker.persistent=false

server.port : 8080

# A thread pool executor dispatcher, named threadPoolExecutor
#reactor.dispatchers.threadPoolExecutor.type : threadPoolExecutor
#reactor.dispatchers.threadPoolExecutor.size : 512
# Backlog is how many Task objects to warm up internally
#reactor.dispatchers.threadPoolExecutor.backlog : 256

#server.tomcat.max-threads : 50
management.endpoints.web.exposure.include : metrics,prometheus

#server.jetty.acceptors= # Number of acceptor threads to use.
#server.jetty.max-http-post-size=0 # Maximum size in bytes of the HTTP post or put content.
#server.jetty.selectors= # Number of selector threads to use.
